name: Hello World Action

# Trigger this action whenever code is pushed to the repository
on:
  push:
    branches:
      - main  # Run only for pushes to the 'main' branch

# Define the steps for this workflow
jobs:
  say-hello:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository code

      - name: Print Hello World
        run: echo "Hello, World! This is my first GitHub Action!"
